spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: mongo
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
      database: oauth
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
    username: default
    password: ${REDIS_PASSWORD}
  security:
    hash: ${SECRET_JWT}
    user:
      name: admin
      password: user123

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
